apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
build:
  local: 
    push: false
  artifacts:
    - image: fadhilaf/auth-ticketing-test
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: fadhilaf/client-ticketing-test
      context: client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '**/*.{tsx,css}'
            dest: .
