apiVersion: apps/v1
kind: Deployment 
metadata:
  name: auth-depl 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: auth 
  template: 
    metadata:
      labels: 
        app: auth 
    spec: 
      containers: 
        - name: auth 
          image: fadhilaf/auth-ticketing-test
          env: 
          - name: JWT_KEY #nama env variable yg mau dipake image ini (for kubernetes log purpose)
            valueFrom: 
              secretKeyRef: 
                name: jwt-secret #nama object secret yg mau dipakai 
                key: JWT_KEY #nama key yg mau diambil valueny (harus dari object yg namany jwt-secret)
          - name: MONGO_URI
            value: 'mongodb://auth-mongo-srv:27017/ticket' #value langsung tanpa object secret kubernetes
--- 
apiVersion: v1 
kind: Service #type service default itu ClusterIP
metadata: 
  name: auth-srv 
spec: 
  selector: 
    app: auth
  ports: 
  - name: auth 
    protocol: TCP
    port: 3000
    targetPort: 3000
